export const USERID_TO_STORE = "USERID_TO_STORE";
export const USERNICKNAME_TO_STORE = "USERNICKNAME_TO_STORE";
export const USERICON_TO_STORE = "USERICON_TO_STORE";
export const MESSAGE_TO_STORE = "MESSAGE_TO_STORE";
export const DELETE_USER_TO_STORE = "DELETE_USER_TO_STORE";
export const DELETE_ALL_MESSAGES_TO_STORE = "DELETE_ALL_MESSAGES_TO_STORE";
export const MESSAGE_TO_STORE_AFTER_DELETE = "MESSAGE_TO_STORE_AFTER_DELETE";
